# Generated by Django 4.2 on 2023-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_kitob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(choices=[('Madina', 'Madina'), ('Malika', 'Malika')], max_length=50)),
                ('ish_vaqti', models.CharField(choices=[('8:00 dan 12:00 gacha', '8:00 dan 12:00 gacha'), ('12:00 dan 17:00 gacha', '12:00 dan 17:00 gacha')], max_length=50)),
            ],
        ),
    ]
