# Generated by Django 4.2 on 2023-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='olingan_sana',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytargan_sana',
            field=models.CharField(max_length=50),
        ),
    ]
