# Generated by Django 4.2 on 2023-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_alter_record_olingan_sana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='qaytargan_sana',
        ),
        migrations.AlterField(
            model_name='record',
            name='olingan_sana',
            field=models.DateField(),
        ),
    ]
