# Generated by Django 4.2 on 2023-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0008_record_qaytargan_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='olingan_sana',
            field=models.DateField(null=True),
        ),
    ]
