# Generated by Django 4.2 on 2023-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0010_record_foydalanuvchi_talaba_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='kitob_soni',
            field=models.SmallIntegerField(null=True),
        ),
    ]
